---
- hosts: all
  become: true

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  tasks:
    - name: "Whoami"
      raw: whoami
      register: whoami
    #- name: get the username running the deploy
    #  local_action: command whoami
    #  register: username_on_the_host

    - debug: var=whoami

    - name: "Update APT packages"
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600
  
